# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf71acf638ded8e0ce4d3b4805293596dfec32ace86e5f565d97e33102eab86088bdef8948608f8801ee5d90ea4032407e20d6063af99461afa086b3ad797e44

test:
  secret_key_base: 2f86d5d5d313809d950bab94f6b8fdf15aac231a115b2dcd5a45721e014cb2cd6c2d6ec388afe4134f95bd2133a63641f08dc125fef1a7f0d7fd5deaead53d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
